### PR TITLE
add an option to the client to sign the request. This is useful for F…

### PR DESCRIPTION
**Pull request by ericfuxealth**
…HIR store such as AWS healthlake.

### CODE REVIEW

**Comment by bkaney** [comment]
@ericfuxealth - Does each individual request need to be signed each time with a new signature, or can you create one signature once up front and use for any subsequent request?

If if is the latter, I think creating the signature and passing into the constructor (as `additionHeaders`) would do the trick.

**Comment by bkaney** [comment]
I think reading through this - https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html - it seems each request would have to be signed each request.

**Comment by ericfuxealth** [comment]
> I think reading through this - https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html - it seems each request would have to be signed each request.

Each request has to be signed separately because the current timestamp is included in the signature.

**Comment by ericfuxealth** [comment]
@bkaney any update on this PR review?

**Comment by shravan097** [comment]
@bkaney  Any update on this? I am also waiting for this PR to get merge

**Comment by bkaney** [comment]
@shravan097 @ericfuxealth I will work on this today. I would like to add an `@example` to the JSDoc for the constructor though. Do you think you could do that?

**Comment by sdhakal-xealth** [comment]
@bkaney Let us know if any further changes are necessary

**Comment by bkaney** [comment]
Replaced by https://github.com/Vermonster/fhir-kit-client/pull/166

**Pull request closed without merging**
